spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hexagonal_server?currentSchema=ledger
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  port: 8082