spring:
  datasource:
    url: jdbc:h2:mem:hexagonal_architecture_server;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=FALSE;MODE=PostgreSQL
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false